version: '3'
services:
  app:
    image: ghcr.io/robinrietdijk/ieq2_backend/ieg06_backend:latest
    container_name: ieq2g06_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
