name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry, Build and Push image
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
  
    - name: Set repository name to lowercase
      id: set-repo-name
      run: |
        repo_name_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=repo_name_lowercase::$repo_name_lowercase"

    - name: Get commit hash
      id: get-commit-hash
      run: |
        commit_hash=$(git rev-parse --short HEAD)
        echo "::set-output name=commit_hash::$commit_hash"

    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ steps.set-repo-name.outputs.repo_name_lowercase }}:${{ steps.get-commit-hash.outputs.commit_hash }}, ghcr.io/${{ github.repository_owner }}/${{ steps.set-repo-name.outputs.repo_name_lowercase }}:latest
