name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    env:
      COMMIT_HASH: $(git rev-parse --short HEAD)
      REPO: ${{ github.repository }}

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
  
    - name: Set repository to lowercase
      run: |
        repo_lowercase=$(echo "${REPO}" | tr '[:upper:]' '[:lower:]')
        echo "REPO_LOWER=${repo_lowercase}" >> $GITHUB_ENV

    - name: Set commit hash in environment file
      run: echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.REPO_LOWER }}/ieg06_backend:${{ env.COMMIT_HASH }},ghcr.io/${{ env.REPO_LOWER }}/ieg06_backend:latest
